#!/bin/bash
cd /Users/imac/data/Projects/jHardwareFX
mvn clean package -e
cd target
rm PcInfoJFX-2.0.jar
mv PcInfoJFX-2.0-spring-boot.jar PcInfoJFX-2.0.jar
7za a -t7z -mx=9 -mfb=273 -ms -md=31 -myx=9 -mtm=- -mmt -mmtf -md=1536m -mmf=bt3 -mmc=10000 -mpb=0 -mlc=0 PcInfoJFX-2.0.7z PcInfoJFX-2.0.jar
